spring.application.name=Choosenfly-Hotel-Booking-System

server.port=8081

spring.profiles.active=test

# IWTX API Configuration
iwtx.api.url=https://api.iwtxconnect.com/hotel/api/v1/search
iwtx.api.availability.url=https://api.iwtxconnect.com/hotel/availability
iwtx.api.password=C0nN3cTW0rLd_2O23
iwtx.api.code=Connect_World
iwtx.api.token=1d11cf19-fc8b-4d58-b590-a048bc601f81-20230516

# X3 API Configuration
x3.api.url=https://api.iwtxconnect.com/hotel/api/v1/search
x3.api.availability.url=https://api.iwtxconnect.com/hotel/availability
x3.api.password=WlHHgkHwxbJtm3bM
x3.api.code=Connect_World_X3
x3.api.token=1d11cf19-fc8b-4d58-b590-a048bc601f81-20230516

# Show SQL queries
spring.jpa.show-sql=true

# Format SQL queries for better readability
spring.jpa.properties.hibernate.format_sql=true