spring.application.name=Choosenfly-Hotel-Booking-System

server.port=8081

spring.profiles.active=test

# IWTX API Configuration
iwtx.api.url=https://api.iwtxconnect.com/hotel/api/v1/search
iwtx.api.password=C0nN3cTW0rLd_2O23
iwtx.api.code=Connect_World
iwtx.api.token=1d11cf19-fc8b-4d58-b590-a048bc601f81-20230516


