# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hotelbookingsystem
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration (Optional but Recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool Settings (Optional, using HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

server.port=8081


spring.mail.host=smtp-relay.sendinblue.com
spring.mail.port=587
spring.mail.username=reservations@choosenfly.in
spring.mail.password=N0KgTXHEvBxUIwrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.email=email-queue
rabbitmq.exchange=email-exchange
rabbitmq.routingkey=email-routing-key



# Comma-separated list of hotel APIs enabled (used to dynamically create queues and bindings)
rabbitmq.hotel.apis=iwtx,api2,api3,api4,api5

# Common exchange for hotel APIs
rabbitmq.hotel.exchange=hotel-exchange

# Routing keys for each hotel API (must align with your dynamic logic)
rabbitmq.hotel.routingkey.iwtx=hotel.iwtx.routingKey
rabbitmq.hotel.routingkey.api2=hotel.api2.routingKey
rabbitmq.hotel.routingkey.api3=hotel.api3.routingKey
rabbitmq.hotel.routingkey.api4=hotel.api4.routingKey
rabbitmq.hotel.routingkey.api5=hotel.api5.routingKey




spring.redis.host=localhost
spring.redis.port=6379
# Optional
spring.redis.timeout=6000
spring.cache.type=redis


agent.api.mapping.1=iwtx,api2,api3
agent.api.mapping.2=iwtx,api4,api5

jwt.secret=secretkeyforsubinsjwtworkforglobosoftspringbootwebapploginmoduledonecorrectlyconfidently

file.upload.directory=D:/akhil sajeev/save/


# refresh token settings
app.refresh.token.byte-size=64
app.refresh.token.hash-salt=some-secret-salt-if-desired
app.refresh.token.expiry-seconds=604800

# cookie settings

app.refresh.cookie.name=refreshToken
# set true in production (requires HTTPS)
app.refresh.cookie.secure=false
app.refresh.cookie.max-age-seconds=604800

